version: "3"
services:
  web:
    build: .
    restart: on-failure
    env_file:
      - ./.env.prod
    command: gunicorn --bind 0.0.0.0:8000 devLobbyWebApplication.wsgi
    ports:
      - "8000:8000"
    depends_on:
      - nginx
  nginx:
    image: "nginx"
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
    ports:
      - "80:80"