version: "3.4"
services:
  web:
    build: .
    restart: on-failure
    env_file:
      - ./.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/www
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: "mysql:5.6"
    command: --init-file /var/lib/mysql/data/init.sql
    env_file:
     - ./.env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql/data